### ISSUE TITLE
Non power of 2 FFT

### ISSUE THREAD

**Issue by tkgunaratne** [goualard-f/MicroFloatingPoints.jl#2]
Thanks for this wonderful package. I'm trying evaluate the signal degradation in various signal processing applications, such as channelization. I managed to evaluate fft to power of 2 number of samples in the input using 'FastTransforms and GenericFFT' Julia packages. However, for non power of 2 number of samples it throws the following error:

`ERROR: MethodError: no method matching Floatmu{8, 23}(::Irrational{:π})
Closest candidates are:
  (::Type{T})(::Real, ::RoundingMode) where T<:AbstractFloat at rounding.jl:200
  (::Type{T})(::T) where T<:Number at boot.jl:772
  (::Type{T})(::AbstractChar) where T<:Union{AbstractChar, Number} at char.jl:50`

I wonder whether you can modify the Package to facilitate non power of 2 ffts.

**Comment by goualard-f** [comment]
Hello,

From the look of it, your program is trying to create a `Floatmu` from an irrational (π, here). Since it will need to be rounded anyway to be stored in a `Floatmu`, can't you just cast the parameter into a `Float64` beforehand (e.g., `Floatmu{8,23}(Float64(π))`) ? Or am I missing something ?

As a (possibly irrelevant)  side note, you will get better performances with `Float32` than with `Floatmu{8,23}`.

Cheers,
F.

**Comment by tkgunaratne** [comment]
Thank you for your response. Let me try to elaborate the issue I'm having. I'm trying to estimate the SNR of FFT operation evaluated with low-precision floating point arithmetic. Your 'MicroFloatingPoints.jl' along with 'FastTransforms'  is greatly helpful in doing so for power of two number of samples. I want to evaluate the FFT of use non-power of two number of samples, for example using the code:

```julia
using MicroFloatingPoints, Statistics
using FastTransforms

#Configuring the MicroFloatingPoints
# Float16, the IEEE 754 half-precision format: Floatmu{5,10}
# Float32, the IEEE 754 single precision format: Floatmu{8,23}
# bfloat16, the Brain Floating Point by Google: Floatmu{8,7}
# TensorFloat-32 the format by NVIDIA or bfloat16+ by Intel: Floatmu{8,10}
# AMD's fp24: Floatmu{7,16}
# Pixar's PXR24: Floatmu{8,15}
TF32 = Floatmu{5,10};

# Generate input data
N = 20; # 2^10;

#x = randn(Float64, N);
x = (randn(Float64, N) + im*randn(Float64, N))/sqrt(2);

# Evaluate FFT with Float6
X_F64 = fft(x);

# Convert input data to TF32 and evaluate FFT
#x_TF32 = TF32.(real(x));
x_TF32 = complex.(TF32.(real(x)), TF32.(imag(x)));

@time X_TF32 = fft(x_TF32);
X_R = Float64.(real(X_TF32)) +im*Float64.(imag(X_TF32)); 


# Compute MSE and SNR
Error_F = X_F64 - X_R;
Max_E_F = maximum(abs.(Error_F));
SNR_E_F = 10log10(var(X_R) / var(Error_F))

println("\nMaximum Error in $N-point FFT $Max_E_F")
println("The Relative Error Power in FFT Output $SNR_E_F dB\n")
```

```
MethodError: no method matching Floatmu{5, 10}(::Irrational{:π})
Closest candidates are:
  (::Type{T})(::Real, ::RoundingMode) where T<:AbstractFloat at rounding.jl:200
  (::Type{T})(::T) where T<:Number at boot.jl:772
  (::Type{T})(::AbstractChar) where T<:Union{AbstractChar, Number} at char.jl:50
```

I wonder is there anything can be modified in the  'MicroFloatingPoints.jl' to define Floatmu{nx, ny}(::Irrational{:π})?

Best Regards,

T

**Comment by goualard-f** [comment]
I have pushed modifications of the package to the main branch. I have tested the new version with your code. I get a result, even though I cannot vouch for its correction. Can you confirm it is ok with you before I release a new version?

**Comment by tkgunaratne** [comment]
Thank you very much for your prompt action. Yes! I just managed to verify the operation.  I really appreciate your support!!
