### ISSUE TITLE
Error when trying to evaluate non-power of 2 FFTs of MicroFloatingPoint vector using GenericFFT.jl

### ISSUE THREAD

**Issue by tkgunaratne** [goualard-f/MicroFloatingPoints.jl#4]
Hi,

I get an error when I try to evaluate fft of a MicroFloatingPoint vector using GenericFFT.jl. I raised an [issue ](https://github.com/JuliaApproximation/GenericFFT.jl/issues/47#issue-2373379491) in the GitHub repo of GenericFFT.jl. I wonder whether it can be resolved with a simple modification in MicroFloatingPoints?

Thanks!

T

**Comment by goualard-f** [comment]
That is weird. It seems the call to `fft()` works when the array of `Floatmu()` has a size which is a power of 2:
```julia
julia> fft(rand(Floatmu{3,5},8))
   3.88 + 0.0im
 -0.211 - 0.875im
 -0.375 + 0.25im
  0.406 + 0.688im
    0.0 + 0.0im
  0.398 - 0.688im
 -0.375 - 0.25im
 -0.219 + 0.875im
```

But it does not otherwise:
```julia
julia> fft(rand(Floatmu{3,5},3))
ERROR: MethodError: no method matching _conv!(::Vector{Complex{Floatmu{3, 5}}}, ::Vector{ComplexF64})

Closest candidates are:
  _conv!(::AbstractVector{T}, ::AbstractVector{T}) where T<:Union{AbstractFloat, Complex{T} where T<:AbstractFloat}
```

**Comment by tkgunaratne** [comment]
I recall that it used to work with both power of 2 and non-power of 2 sample points.

**Comment by goualard-f** [comment]
I tracked down the problem to a change in the [generic_fft()](https://github.com/JuliaApproximation/GenericFFT.jl/blob/87af31f2cdf39f806be41cdc271f2204e9a43dd3/src/fft.jl#L59) function of the GenericFFT package. The latest version uses `cispi()`. For a `Floatmu{}` or `Complex(Floatmu{}` argument, that function returns a `Complex{Float64}` value. I'll try to add support in MicroFloatingPoints for that function soon.

**Comment by goualard-f** [comment]
@tkgunaratne I have added the `sincospi()` function to the `Floatmu{}` type. Can you confirm that the current code on Github works to your satisfaction?

**Comment by tkgunaratne** [comment]
@goualard-f , Thank you very much for your quick response. I conform that non-power of 2 ffts can be computed for  MicroFloatingPoints.
